name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=4.0
  - python=3.10
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - pip
  - pip:
    - plotly 
    - scikit-learn
    - numpy
    - pandas
    - matplotlib  
    - numpy
    - pytorch
